//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by citafoil.rc
//
#define IDD_ABOUTBOX				100
#define IDR_POPUP_EDIT				119
#define ID_STATUSBAR_PANE1			120
#define ID_STATUSBAR_PANE2			121
#define IDS_STATUS_PANE1			122
#define IDS_STATUS_PANE2			123
#define IDS_TOOLBAR_STANDARD		124
#define IDS_TOOLBAR_CUSTOMIZE		125
#define ID_VIEW_CUSTOMIZE			126
#define IDR_MAINFRAME				128
#define IDR_MAINFRAME_256			129
#define IDR_citafoilTYPE				130
#define ID_VIEW_PROPERTIESWND		150
#define ID_SORTPROPERTIES			151
#define ID_PROPERTIES1				152
#define ID_PROPERTIES2				153
#define ID_EXPAND_ALL				154
#define IDS_PROPERTIES_WND			158
#define IDI_PROPERTIES_WND			167
#define IDI_PROPERTIES_WND_HC		168
#define IDR_PROPERTIES				183
#define IDB_PROPERTIES_HC			184
#define IDS_EDIT_MENU				306
#define IDR_COMBOBOX_AIRFOILS		400

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	310
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		310
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
